### PR TITLE
updated feedstock to v1.5.2.230105

### PR DESCRIPTION
**Pull request by Dr-Irv**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [N/A] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Dr-Irv** [comment]
@conda-forge-admin, please rerender

**Comment by twoertwein** [comment]
I don't know why it doesn't autogenerate the PRs anymore. I think you probably also need to adjust the sha256 checksum.

**Comment by Dr-Irv** [comment]
This is failing due to the source not being found on pypi.org:  See https://github.com/pypi/warehouse/issues/12776

**Comment by Dr-Irv** [comment]
> I don't know why it doesn't autogenerate the PRs anymore. I think you probably also need to adjust the sha256 checksum.

Thanks for the sha256 checksum pointer.

Apparently `poetry build` changed the name of our source tar from `pandas-stubs` to `pandas_stubs`.  See https://github.com/python-poetry/poetry/issues/7314

**Pull request merged**
