### PR TITLE
Make noarch and remove poetry from run requirements

### PR DESCRIPTION
**Pull request by adament**
As far as I can tell the package is purely typing stubs and thus should
be suitable for a noarch package, furthermore the wheel on pypi is also
noarch. Instead I introduced a python >=3.8 version constraint to
match the previous skip constraint.

Poetry was added in #95 as both a build, host and run dependency. As far
as I can tell it should not be necessary to add it as a runtime
dependency and it pulls in a lot of other dependencies when installed so
if possible it would be nice to avoid having it as a runtime dependency.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by zkrolikowski-vl** [comment]
Hi @adament. Thanks for proposing those changes.

The only reason why I went to make it architecture dependent was that I found it impossible to only force `typing_extensions` installation for Py<3.8.

This change disallows <3.8 (which already has been decided), so `typing_extensions` might not be necessary.

You probably know better @Dr-Irv

**Comment by adament** [comment]
Ah that makes sense, but since #95 the inequality was reversed and it requires `typing_extensions` for python greater than or equal to 3.8 which is also the base python requirement, so I do not think there is any need for an architecture dependent package anymore. As far as I can tell this also matches upstream.

**Review by Dr-Irv — APPROVED** [review]
Thanks for the help.  My first time doing any of this kind of stuff.

**Pull request merged**
